// ============================================================
// THE PORTAL'S OWN WORDS
//
// Every word the portal draws itself lives here in English and
// Spanish. Help's answers and the two report forms are not in
// this file: those arrive from the API already in the chosen
// language.
//
// The key is the exact English a screen shows today. A reviewer
// reads each pair side by side in translation/portal_words.csv,
// and a key with no entry falls back to the English, so a word
// added later shows in English rather than blank or as a code.
//
// Accented letters and opening marks are written as \u escapes,
// so this file stays ASCII while the screen shows correct
// Spanish. The review sheet is the file written in real Spanish
// characters, because people read that one.
// ============================================================

// The language every screen reads. The root component sets it
// from the one piece of state Step 70 already keeps, during its
// own render, so the choice is in place before any screen below
// renders and choosing Spanish in Settings changes the whole
// portal at once with no reload. A module value rather than a
// context, because a good half of the portal's words are drawn
// by plain helper functions that cannot hold a hook.
let current = "en";

export function setWordsLanguage(lang) {
  current = lang === "es" ? "es" : "en";
}

export function wordsLanguage() {
  return current;
}

// English is the key, so there is no English table.
export const WORDS = {
  es: {
  // Sign in
  "2155550000 (no dashes needed)": "2155550000 (sin guiones)",
  "4-digit PIN": "PIN de 4 d\u00edgitos",
  "9001, 2155550101 or name@email.com": "9001, 2155550101 o nombre@correo.com",
  "Account Activation": "Activaci\u00f3n de cuenta",
  "Activate Account": "Activar cuenta",
  "Activating...": "Activando...",
  "and can be used once.": "y se puede usar una sola vez.",
  "Ask your supervisor to confirm your badge number.": "Pida a su supervisor que confirme su n\u00famero de empleado.",
  "Back to Login": "Volver al inicio de sesi\u00f3n",
  "Back to Sign In": "Volver al inicio de sesi\u00f3n",
  "Badge Number": "N\u00famero de empleado",
  "Badge number": "N\u00famero de empleado",
  "Badge Number, Phone or Email": "N\u00famero de empleado, tel\u00e9fono o correo",
  "Checking your link...": "Revisando su enlace...",
  "Choose your new 4-digit PIN.": "Elija su nuevo PIN de 4 d\u00edgitos.",
  "Confirm PIN": "Confirmar PIN",
  "Confirm PIN *": "Confirmar PIN *",
  "Confirm your badge number and choose your 4-digit PIN.": "Confirme su n\u00famero de empleado y elija su PIN de 4 d\u00edgitos.",
  "Contact your supervisor to have a new link sent.": "Hable con su supervisor para que le env\u00eden un enlace nuevo.",
  "Could not reach OCSA. Check your connection and try again.": "No se pudo conectar con OCSA. Revise su conexi\u00f3n e intente de nuevo.",
  "Dark Mode": "Modo oscuro",
  "Email Address": "Correo electr\u00f3nico",
  "Email Address *": "Correo electr\u00f3nico *",
  "Enter the badge number, phone number or email address on your account and we will email you a link to choose a new PIN.": "Escriba el n\u00famero de empleado, tel\u00e9fono o correo de su cuenta y le enviaremos un enlace para elegir un PIN nuevo.",
  "Enter your badge number, phone number or email address.": "Escriba su n\u00famero de empleado, tel\u00e9fono o correo electr\u00f3nico.",
  "Fill in {field}.": "Complete {field}.",
  "First Name": "Nombre",
  "First name": "Nombre",
  "First Name *": "Nombre *",
  "Forgot your PIN?": "\u00bfOlvid\u00f3 su PIN?",
  "Forgotten your badge number? You can also sign in with your phone number or your email address.": "\u00bfOlvid\u00f3 su n\u00famero de empleado? Tambi\u00e9n puede entrar con su tel\u00e9fono o su correo electr\u00f3nico.",
  "If that matches an account on file, a reset link is on its way. The link is good for one hour.": "Si eso coincide con una cuenta registrada, le enviamos un enlace. El enlace sirve por una hora.",
  "If you do not have an email address on file, no link can reach you. Contact your supervisor to have your PIN reset directly.": "Si no tiene un correo registrado, no hay c\u00f3mo enviarle el enlace. Hable con su supervisor para que le restablezca el PIN directamente.",
  "Language": "Idioma",
  "Last Name": "Apellido",
  "Last name": "Apellido",
  "Light Mode": "Modo claro",
  "Loading...": "Cargando...",
  "name@email.com": "nombre@correo.com",
  "New Employee? Register Here": "\u00bfEmpleado nuevo? Reg\u00edstrese aqu\u00ed",
  "New PIN (4 digits)": "PIN nuevo (4 d\u00edgitos)",
  "New Staff Registration": "Registro de personal nuevo",
  "Not you? Sign out": "\u00bfNo es usted? Cerrar sesi\u00f3n",
  "Phone Number": "N\u00famero de tel\u00e9fono",
  "Phone Number *": "N\u00famero de tel\u00e9fono *",
  "PIN": "PIN",
  "PIN (4 digits)": "PIN (4 d\u00edgitos)",
  "PIN (4 digits) *": "PIN (4 d\u00edgitos) *",
  "PIN saved. Signing you in...": "PIN guardado. Iniciando su sesi\u00f3n...",
  "PIN set. Signing you in...": "PIN guardado. Iniciando su sesi\u00f3n...",
  "Register": "Registrarse",
  "Registering...": "Registrando...",
  "Request a New Link": "Pedir un enlace nuevo",
  "Reset Your PIN": "Restablecer su PIN",
  "Save PIN": "Guardar PIN",
  "Saving...": "Guardando...",
  "Send Reset Link": "Enviar enlace",
  "Sending...": "Enviando...",
  "Set your own PIN. The PIN you were given is known to your supervisor. Choose a new one that only you know.": "Elija su propio PIN. Su supervisor conoce el PIN que le dieron. Elija uno nuevo que solo usted sepa.",
  "Set Your PIN": "Elija su PIN",
  "Sign In": "Iniciar sesi\u00f3n",
  "Signing in will work once your account is active.": "Podr\u00e1 iniciar sesi\u00f3n cuando su cuenta est\u00e9 activa.",
  "Signing in...": "Iniciando sesi\u00f3n...",
  "Something went wrong on our end. Try again in a minute.": "Hubo un problema de nuestro lado. Intente de nuevo en un minuto.",
  "Staff Operations Portal": "Portal del Personal",
  "That badge number does not match our records. Check the number in your email.": "Ese n\u00famero de empleado no coincide con nuestros registros. Revise el n\u00famero en su correo.",
  "The number on the email we sent you.": "El n\u00famero que aparece en el correo que le enviamos.",
  "The two PINs do not match. Type the same 4 digits in both fields.": "Los dos PIN no coinciden. Escriba los mismos 4 d\u00edgitos en las dos casillas.",
  "This activation link is incomplete. Open the link from your email again.": "Este enlace de activaci\u00f3n est\u00e1 incompleto. Abra el enlace de su correo otra vez.",
  "This link is no longer valid. Links expire, and each one can only be used once.": "Este enlace ya no sirve. Los enlaces vencen y cada uno se puede usar una sola vez.",
  "This link works until": "Este enlace sirve hasta",
  "This reset link is incomplete. Open the link from your email again.": "Este enlace de restablecimiento est\u00e1 incompleto. Abra el enlace de su correo otra vez.",
  "Try Again": "Intentar de nuevo",
  "Welcome back, {name}.": "Bienvenido de nuevo, {name}.",
  "Welcome, {name}.": "Bienvenido, {name}.",
  "Your account is activated but not currently active. Contact your supervisor.": "Su cuenta est\u00e1 activada pero no est\u00e1 activa en este momento. Hable con su supervisor.",
  "Your PIN has been changed. Contact your supervisor about your account status.": "Su PIN fue cambiado. Hable con su supervisor sobre el estado de su cuenta.",
  "Your PIN has been saved. Signing in will work once your account is active.": "Su PIN se guard\u00f3. Podr\u00e1 iniciar sesi\u00f3n cuando su cuenta est\u00e9 activa.",
  "PIN must be exactly 4 digits.": "El PIN debe tener exactamente 4 d\u00edgitos.",
  "Four of the same digit is too easy to guess. Use a mix of digits.": "Cuatro d\u00edgitos iguales son muy f\u00e1ciles de adivinar. Use d\u00edgitos distintos.",
  "Digits in a row, like 1234 or 4321, are too easy to guess. Use a different order.": "Los d\u00edgitos seguidos, como 1234 o 4321, son muy f\u00e1ciles de adivinar. Use otro orden.",
  "Your PIN cannot be your badge number or its last four digits.": "Su PIN no puede ser su n\u00famero de empleado ni sus \u00faltimos cuatro d\u00edgitos.",
  "Enter the badge number from your email.": "Escriba el n\u00famero de empleado que aparece en su correo.",

  // App wide
  "A new version is ready": "Hay una versi\u00f3n nueva lista",
  "Add {app} to your home screen": "Agregue {app} a su pantalla de inicio",
  "Confirm on the next screen.": "Confirme en la siguiente pantalla.",
  "Copied": "Copiado",
  "Copy address": "Copiar la direcci\u00f3n",
  "Could not find your open shift. Reload and try again.": "No se encontr\u00f3 su turno abierto. Recargue e intente de nuevo.",
  "Don't show again": "No mostrar m\u00e1s",
  "Edit shortcuts": "Editar accesos directos",
  "End your shift at {site}?": "\u00bfTerminar su turno en {site}?",
  "Extra large": "M\u00e1s grande",
  "Install": "Instalar",
  "Issue reported": "Problema reportado",
  "It opens like an app, one tap from your home screen.": "Se abre como una aplicaci\u00f3n, con un toque desde su pantalla de inicio.",
  "Large": "Grande",
  "Largest": "El m\u00e1s grande",
  "Low stock alert!": "\u00a1Aviso de poco inventario!",
  "More": "M\u00e1s",
  "Not now": "Ahora no",
  "Notifications": "Notificaciones",
  "ON SITE": "EN SITIO",
  "Open the browser menu. It is usually three dots at the top right.": "Abra el men\u00fa del navegador. Casi siempre son tres puntos arriba a la derecha.",
  "PIN updated": "PIN actualizado",
  "Profile": "Perfil",
  "Registration submitted. Pending supervisor approval.": "Registro enviado. Pendiente de aprobaci\u00f3n de su supervisor.",
  "Request submitted": "Solicitud enviada",
  "Scroll down and tap Add to Home Screen.": "Baje y toque Agregar a la pantalla de inicio.",
  "Select a site first": "Primero elija un sitio",
  "Settings": "Ajustes",
  "Shift ended": "Turno terminado",
  "Shift ended at {time}": "Turno terminado a las {time}",
  "Shift started": "Turno iniciado",
  "Shortcuts saved": "Accesos directos guardados",
  "Sign out": "Cerrar sesi\u00f3n",
  "Standard": "Normal",
  "Tap Add or Install.": "Toque Agregar o Instalar.",
  "Tap Add to Home screen or Install app.": "Toque Agregar a la pantalla de inicio o Instalar aplicaci\u00f3n.",
  "Tap Add to Home Screen.": "Toque Agregar a la pantalla de inicio.",
  "Tap Add.": "Toque Agregar.",
  "Tap Install below.": "Toque Instalar abajo.",
  "Tap the Share button {share} at the bottom of the screen.": "Toque el bot\u00f3n Compartir {share} abajo en la pantalla.",
  "Tap the Share button {share} in the address bar.": "Toque el bot\u00f3n Compartir {share} en la barra de direcciones.",
  "Task completed": "Tarea completada",
  "Task unchecked": "Tarea desmarcada",
  "Task updated to {status}": "Estado de la tarea: {status}",
  "That sign-in did not match. Check your badge, phone or email and your PIN.": "Esos datos no coinciden. Revise su n\u00famero de empleado, tel\u00e9fono o correo y su PIN.",
  "This page is open inside another app. Open it in Safari or Chrome first, then add it to your home screen.": "Esta p\u00e1gina est\u00e1 abierta dentro de otra aplicaci\u00f3n. \u00c1brala primero en Safari o Chrome y luego agr\u00e9guela a su pantalla de inicio.",
  "This shift was already ended": "Este turno ya estaba terminado",
  "this site": "este sitio",
  "Update now": "Actualizar ahora",
  "Welcome, {name}": "Bienvenido, {name}",
  "{count} unread notifications": "{count} notificaciones sin leer",
  "{brand} Staff Portal": "Portal del Personal de {brand}",
  "Could not read image": "No se pudo leer la imagen",
  "Compression failed": "No se pudo preparar la foto",
  "Custodian": "Conserje",
  "Custodial Lead": "L\u00edder de conserjes",
  "Lead": "L\u00edder",
  "Supervisor": "Supervisor",
  "Admin": "Administrador",
  "in progress": "en proceso",
  "resolved": "resuelta",
  "unable to resolve": "sin resolver",

  // Home
  "All Other Sites": "Todos los dem\u00e1s sitios",
  "Choose a Site to Start": "Elija un sitio para comenzar",
  "Drop requested": "Pidi\u00f3 dejarlo",
  "End Shift": "Terminar turno",
  "Ending...": "Terminando...",
  "Floor {n}": "Piso {n}",
  "Loading sites...": "Cargando sitios...",
  "No sites available yet.": "Todav\u00eda no hay sitios disponibles.",
  "requested": "solicitada",
  "Scheduled Today": "Programado para hoy",
  "Shift Open at {site}": "Turno abierto en {site}",
  "Start Shift": "Comenzar turno",
  "Start Shift at {site}": "Comenzar turno en {site}",
  "Started at {time}": "Comenz\u00f3 a las {time}",
  "Started {day} at {time}": "Comenz\u00f3 el {day} a las {time}",
  "Starting...": "Comenzando...",
  "Time off": "Tiempo libre",
  "Time on Site": "Tiempo en el sitio",
  "You asked to drop this shift. Waiting for a decision.": "Usted pidi\u00f3 dejar este turno. Espera una decisi\u00f3n.",
  "Your Assigned Sites": "Sus sitios asignados",
  "A shift is still open at {site}. End it before starting another.": "Todav\u00eda hay un turno abierto en {site}. Term\u00ednelo antes de comenzar otro.",
  "A shift is still open. End it before starting another.": "Todav\u00eda hay un turno abierto. Term\u00ednelo antes de comenzar otro.",

  // Schedule
  " (live)": " (en curso)",
  " ({h}h)": " ({h} h)",
  "Any additional details...": "Cualquier detalle adicional...",
  "approved": "aprobado",
  "Approved": "Aprobada",
  "Asked": "Fecha de solicitud",
  "Bereavement and personal": "Duelo y asuntos personales",
  "Building": "Edificio",
  "Cancel": "Cancelar",
  "Cancel request": "Cancelar solicitud",
  "Cancel this time off request?": "\u00bfCancelar esta solicitud de tiempo libre?",
  "Cancelled": "Cancelada",
  "Choose a type": "Elija un tipo",
  "claimed": "tomado",
  "Close": "Cerrar",
  "Completed": "Completado",
  "Dates": "Fechas",
  "Decided": "Fecha de decisi\u00f3n",
  "Denied": "Denegada",
  "Describe the reason": "Describa el motivo",
  "Drop Request": "Solicitud para dejar el turno",
  "Drop request failed": "No se pudo enviar la solicitud",
  "Drop request sent. Your supervisor will review it.": "Solicitud enviada. Su supervisor la revisar\u00e1.",
  "Duration": "Duraci\u00f3n",
  "Emergency": "Emergencia",
  "End": "Fin",
  "First day": "Primer d\u00eda",
  "Floor": "Piso",
  "For example, 8": "Por ejemplo, 8",
  "From": "Desde",
  "Hours": "Horas",
  "Hours (optional)": "Horas (opcional)",
  "Jury duty": "Servicio de jurado",
  "Keep it": "Conservarla",
  "Last day": "\u00daltimo d\u00eda",
  "Military leave": "Licencia militar",
  "Month": "Mes",
  "My Schedule": "Mi horario",
  "My time off": "Mi tiempo libre",
  "N/A": "No disponible",
  "No note": "Sin nota",
  "No reason given": "No dio un motivo",
  "No time off requests yet.": "Todav\u00eda no tiene solicitudes de tiempo libre.",
  "Not given": "No indicado",
  "Note": "Nota",
  "Note: {note}": "Nota: {note}",
  "Notes": "Notas",
  "Notes (optional)": "Notas (opcional)",
  "On Site": "En sitio",
  "Only you and the person who approves time off can read this.": "Solo usted y la persona que aprueba el tiempo libre pueden leer esto.",
  "Other": "Otro",
  "Paid sick leave": "Licencia por enfermedad pagada",
  "Part of the day": "Parte del d\u00eda",
  "Personal": "Asunto personal",
  "Pickup": "Turnos libres",
  "Pickup Shift": "Turno tomado",
  "Reason": "Motivo",
  "Reason (optional)": "Motivo (opcional)",
  "Request time off": "Solicitar tiempo libre",
  "Request to Drop This Shift": "Pedir dejar este turno",
  "Requested": "Solicitada",
  "Scheduled": "Programado",
  "Scheduled Shift": "Turno programado",
  "Scheduling Conflict": "Conflicto de horario",
  "Send request": "Enviar solicitud",
  "Service": "Servicio",
  "Shift End": "Fin del turno",
  "Shift Start": "Inicio del turno",
  "Shifts on these days": "Turnos en estos d\u00edas",
  "Showing your latest 50 requests.": "Mostrando sus 50 solicitudes m\u00e1s recientes.",
  "Sick": "Enfermedad",
  "Site": "Sitio",
  "Specify Reason": "Indique el motivo",
  "Start": "Inicio",
  "Status": "Estado",
  "Still on site": "Todav\u00eda en sitio",
  "Submit Request": "Enviar solicitud",
  "Time": "Hora",
  "Time off request": "Solicitud de tiempo libre",
  "Time off request cancelled.": "Solicitud de tiempo libre cancelada.",
  "Time off requested. You get a notice when it is decided.": "Tiempo libre solicitado. Recibir\u00e1 un aviso cuando se decida.",
  "To": "Hasta",
  "Today": "Hoy",
  "Type": "Tipo",
  "Unpaid time off": "Tiempo libre sin pago",
  "Week": "Semana",
  "Worked": "Trabajado",
  "Worked Shift": "Turno trabajado",
  "You get a notice in the app when your request is decided.": "Recibir\u00e1 un aviso en la aplicaci\u00f3n cuando se decida su solicitud.",
  "Your supervisor will review this request. If approved, the shift will be opened for pickup or reassigned.": "Su supervisor revisar\u00e1 esta solicitud. Si la aprueba, el turno se abrir\u00e1 para que otra persona lo tome o se reasignar\u00e1.",
  "{h}h {m}m": "{h} h {m} min",
  "{n} hour": "{n} hora",
  "{n} hours": "{n} horas",
  "{start} to {end}": "{start} a {end}",
  "{start} to {end}, {year}": "{start} a {end}, {year}",
  "Pending": "Pendiente",
  "Claimed": "Tomado",
  "Filled": "Cubierto",

  // Tasks
  "Back to checklist": "Volver a la lista",
  "Due Date:": "Fecha l\u00edmite:",
  "Instructions": "Instrucciones",
  "Loading tasks...": "Cargando tareas...",
  "Mark Complete": "Marcar como completada",
  "Mark {name} done": "Marcar {name} como completada",
  "Mark {name} not done": "Desmarcar {name}",
  "No checklist is set up for this building yet.": "Este edificio todav\u00eda no tiene una lista de tareas.",
  "No tasks loaded. Start your shift at a site to see your checklist.": "No hay tareas. Comience su turno en un sitio para ver su lista.",
  "PRIORITY": "PRIORIDAD",
  "Reference Photo": "Foto de referencia",
  "Reference Video": "Video de referencia",
  "Start your shift to see and check off your tasks.": "Comience su turno para ver y marcar sus tareas.",
  "Task reference": "Referencia de la tarea",
  "Time:": "Hora:",
  "Try again": "Intentar de nuevo",
  "Uncheck Task": "Desmarcar tarea",
  "Your Assignment": "Su asignaci\u00f3n",
  "Your tasks did not load.": "Sus tareas no cargaron.",
  "General": "General",
  "Which shift are you working?": "\u00bfQu\u00e9 turno est\u00e1 trabajando?",
  "Chosen by the time you started. Change it if it is wrong.": "Elegido seg\u00fan la hora en que empez\u00f3. C\u00e1mbielo si no es correcto.",
  "Use this shift": "Usar este turno",
  "Change shift": "Cambiar turno",
  "This week": "Esta semana",
  "Every two weeks": "Cada dos semanas",
  "This month": "Este mes",
  "This quarter": "Este trimestre",
  "This season": "Esta temporada",
  "As needed": "Seg\u00fan se necesite",
  "{done} of {total} done": "{done} de {total} hechas",
  "Done today by {firstName}": "Hecho hoy por {firstName}",
  "Done yesterday by {firstName}": "Hecho ayer por {firstName}",
  "Done {weekday} by {firstName}": "Hecho el {weekday} por {firstName}",
  "Done {date} by {firstName}": "Hecho el {date} por {firstName}",
  "Checked by {firstName}": "Marcado por {firstName}",
  "Only the person who checked this can uncheck it.": "Solo la persona que marc\u00f3 esta tarea puede desmarcarla.",

  // Chat
  "Admin (Private)": "Administraci\u00f3n (privado)",
  "No chats are set up for you yet. Ask your supervisor.": "Todav\u00eda no hay chats para usted. Pregunte a su supervisor.",
  "No messages yet.": "Todav\u00eda no hay mensajes.",
  "Only you and management can see these messages": "Solo usted y la administraci\u00f3n ven estos mensajes",
  "Pick a chat at the top first.": "Primero elija un chat arriba.",
  "Pick a chat to start.": "Elija un chat para empezar.",
  "Private chats": "Chats privados",
  "Private conversation with admin.": "Conversaci\u00f3n privada con la administraci\u00f3n.",
  "Private message to admin...": "Mensaje privado a la administraci\u00f3n...",
  "Type a message...": "Escriba un mensaje...",
  "You cannot send messages in this chat.": "No puede enviar mensajes en este chat.",
  "Your chats did not load. Try again in a minute.": "Sus chats no cargaron. Intente de nuevo en un minuto.",
  "Your message was not sent.": "Su mensaje no fue enviado.",

  // Help
  "Add a photo": "Agregar una foto",
  "Based on": "Seg\u00fan",
  "Describe what happened": "Describa lo que pas\u00f3",
  "Fill in form": "Llenar formulario",
  "general cleaning guidance": "una gu\u00eda general de limpieza",
  "Not sent.": "No se envi\u00f3.",
  "Remove photo": "Quitar foto",
  "Report in progress": "Reporte en proceso",
  "Report submitted.": "Reporte enviado.",
  "Resume": "Continuar",
  "Retry": "Reintentar",
  "Send": "Enviar",
  "Still needed before you can submit:": "Falta esto antes de poder enviar:",
  "Submit report": "Enviar reporte",
  "Submitting...": "Enviando...",
  "Tell me what happened and I will tell you what to do.": "Cu\u00e9nteme qu\u00e9 pas\u00f3 y le digo qu\u00e9 hacer.",
  "the ADP guide": "la gu\u00eda de ADP",
  "the app guide": "la gu\u00eda de la aplicaci\u00f3n",
  "The connection dropped. Your answer is saved.": "Se perdi\u00f3 la conexi\u00f3n. La respuesta qued\u00f3 guardada.",
  "This photo could not be read here. Choose a JPEG or PNG, or take a screenshot of it.": "Esta foto no se pudo leer aqu\u00ed. Elija un JPEG o PNG, o tome una captura de pantalla.",
  "Unfinished reports": "Reportes sin terminar",
  "Uploading...": "Subiendo...",
  "Working from the written procedure only right now.": "Por ahora solo se est\u00e1 usando el procedimiento escrito.",
  "x": "x",
  "You can send up to 3 photos with one message.": "Puede enviar hasta 3 fotos en un mensaje.",
  "{answered} of {total} answered": "{answered} de {total} respondidas",

  // Assigned
  "A photo of the completed task is required": "Se necesita una foto de la tarea completada",
  "Assigned": "Asignadas",
  "Assigned by": "Asignada por",
  "Assigned Tasks": "Tareas asignadas",
  "at {time}": "a las {time}",
  "Attached Photo": "Foto adjunta",
  "Attached Video": "Video adjunto",
  "Back to assigned tasks": "Volver a las tareas asignadas",
  "Cannot Resolve": "No se puede resolver",
  "Describe the issue preventing completion...": "Describa lo que impide completarla...",
  "Describe the steps you took...": "Describa los pasos que sigui\u00f3...",
  "Describe what you did to complete this task": "Describa lo que hizo para completar esta tarea",
  "Description": "Descripci\u00f3n",
  "Due Date": "Fecha l\u00edmite",
  "Due:": "Para:",
  "Explain why this cannot be completed *": "Explique por qu\u00e9 no se puede completar *",
  "In Progress": "En proceso",
  "ISSUE": "PROBLEMA",
  "Mark as Resolved": "Marcar como resuelta",
  "No assigned tasks right now.": "No hay tareas asignadas en este momento.",
  "Photo must be under 10MB": "La foto debe pesar menos de 10 MB",
  "Photo of completed task *": "Foto de la tarea completada *",
  "Please provide a reason": "Indique un motivo",
  "Preview": "Vista previa",
  "Reported by": "Reportada por",
  "Required to verify completion": "Se necesita para comprobar que se complet\u00f3",
  "Resolved": "Resuelta",
  "Submit": "Enviar",
  "Submit Resolution": "Enviar resoluci\u00f3n",
  "Take Photo of Completed Task": "Tomar foto de la tarea completada",
  "Task": "Tarea",
  "What did you do to complete this? *": "\u00bfQu\u00e9 hizo para completarla? *",
  "When a supervisor assigns a task to you, it will appear here.": "Cuando un supervisor le asigne una tarea, aparecer\u00e1 aqu\u00ed.",
  "{n} task assigned to you": "{n} tarea asignada a usted",
  "{n} tasks assigned to you": "{n} tareas asignadas a usted",
  "Unable to resolve": "Sin resolver",
  "Medium": "Media",
  "Critical": "Cr\u00edtica",

  // Report
  "+ Report": "+ Reportar",
  "Additional details...": "Detalles adicionales...",
  "Brief description": "Descripci\u00f3n breve",
  "Details": "Detalles",
  "e.g. Restroom, Lobby": "por ejemplo: ba\u00f1o, recepci\u00f3n",
  "Enter issue title": "Escriba un t\u00edtulo para el problema",
  "High": "Alta",
  "Issues": "Problemas",
  "JPG, PNG up to 10MB": "JPG o PNG hasta 10 MB",
  "Low": "Baja",
  "Med": "Media",
  "No issues reported yet.": "Todav\u00eda no se ha reportado ning\u00fan problema.",
  "Photo": "Foto",
  "Photo attached:": "Foto adjunta:",
  "Report an Issue": "Reportar un problema",
  "Select a site": "Elija un sitio",
  "Select site...": "Elija un sitio...",
  "Severity": "Gravedad",
  "Submit Issue": "Enviar problema",
  "Take Photo or Choose from Gallery": "Tomar foto o elegir de la galer\u00eda",
  "Title": "T\u00edtulo",
  "Zone": "Zona",
  "Open": "Abierto",
  "Closed": "Cerrado",

  // Supplies
  "+ Request": "+ Solicitar",
  "Damage Report": "Reporte de da\u00f1o",
  "Describe the request...": "Describa la solicitud...",
  "Enter the item name": "Escriba el nombre del art\u00edculo",
  "Item": "Art\u00edculo",
  "Item Name": "Nombre del art\u00edculo",
  "Log Usage": "Registrar uso",
  "Log usage or submit a request": "Registre el uso o env\u00ede una solicitud",
  "LOW": "POCO",
  "New Gear": "Equipo nuevo",
  "One less": "Uno menos",
  "One more": "Uno m\u00e1s",
  "New Supply": "Insumo nuevo",
  "Normal": "Normal",
  "QR": "QR",
  "Refill": "Reposici\u00f3n",
  "Request Type": "Tipo de solicitud",
  "Select a request type": "Elija un tipo de solicitud",
  "Select supply...": "Elija un art\u00edculo...",
  "Start your shift to log usage. Requests can be submitted anytime.": "Comience su turno para registrar el uso. Las solicitudes se pueden enviar en cualquier momento.",
  "Supplies": "Insumos",
  "Supply Item": "Art\u00edculo",
  "Supply Tracking": "Control de insumos",
  "Supply/Gear Request": "Solicitud de insumos o equipo",
  "This Shift's Log": "Registro de este turno",
  "Urgency": "Urgencia",
  "Urgent": "Urgente",
  "What do you need?": "\u00bfQu\u00e9 necesita?",

  // Pickup
  "Approved. You are scheduled for this shift.": "Aprobado. Est\u00e1 programado para este turno.",
  "Available": "Disponibles",
  "Bldg:": "Edificio:",
  "Callout": "Ausencia",
  "Check back later for available pickup shifts at your assigned sites.": "Vuelva m\u00e1s tarde para ver turnos libres en los sitios que tiene asignados.",
  "Claim This Shift": "Tomar este turno",
  "Claiming...": "Tomando...",
  "Extra Coverage": "Cobertura adicional",
  "Floor:": "Piso:",
  "My Pickups": "Los m\u00edos",
  "New Shift": "Turno nuevo",
  "No claimed shifts": "No tiene turnos tomados",
  "No open shifts right now": "No hay turnos libres en este momento",
  "No-Show": "No se present\u00f3",
  "Release Shift": "Soltar turno",
  "Release this shift? It will go back to the open pool for someone else to claim.": "\u00bfSoltar este turno? Volver\u00e1 a la lista abierta para que otra persona lo tome.",
  "Shift claimed (overtime warning: {hours}h this week)": "Turno tomado (aviso de horas extra: {hours} h esta semana)",
  "Shift claimed successfully!": "\u00a1Turno tomado!",
  "Shift Pickup Board": "Turnos libres",
  "Shift released": "Turno soltado",
  "Shifts you claim will appear here.": "Los turnos que tome aparecer\u00e1n aqu\u00ed.",
  "Start your shift at the normal time and your daily tasks will load automatically.": "Comience su turno a la hora de siempre y sus tareas del d\u00eda cargar\u00e1n solas.",
  "URGENT": "URGENTE",
  "Voluntary Drop": "Turno dejado",
  "Waiting for manager approval": "Esperando la aprobaci\u00f3n del gerente",

  // Inspect
  "+ Schedule": "+ Programar",
  "Attach Photo": "Adjuntar foto",
  "General observations, follow-ups needed, etc.": "Observaciones generales, seguimientos pendientes, etc.",
  "Inspection scheduled": "Inspecci\u00f3n programada",
  "Inspection submitted": "Inspecci\u00f3n enviada",
  "Inspections assigned to you will appear here.": "Las inspecciones que le asignen aparecer\u00e1n aqu\u00ed.",
  "My Inspections": "Mis inspecciones",
  "No inspections pending": "No hay inspecciones pendientes",
  "Notes for this item (optional)": "Notas para este punto (opcional)",
  "Overall Notes": "Notas generales",
  "Photo attached": "Foto adjunta",
  "pts": "pts",
  "Running total": "Total acumulado",
  "Schedule Inspection": "Programar inspecci\u00f3n",
  "Scheduled Date *": "Fecha programada *",
  "Scheduling...": "Programando...",
  "Select template...": "Elija una plantilla...",
  "Site *": "Sitio *",
  "Submit Inspection": "Enviar inspecci\u00f3n",
  "Tap an inspection to begin scoring.": "Toque una inspecci\u00f3n para empezar a calificar.",
  "Tap to start scoring": "Toque para empezar a calificar",
  "Template *": "Plantilla *",
  "Template, site, and date are required": "Se necesitan la plantilla, el sitio y la fecha",

  // Speak Up
  "Anyone you pick below will not be able to see this report.": "Nadie que usted elija abajo podr\u00e1 ver este reporte.",
  "Is this about someone in management?": "\u00bfEs sobre alguien de la gerencia?",
  "No": "No",
  "No one matches that name.": "Nadie tiene ese nombre.",
  "Nothing you write here is kept. If you leave this screen before you send, it is gone.": "Nada de lo que escriba aqu\u00ed se guarda. Si sale de esta pantalla antes de enviar, se pierde.",
  "Optional": "Opcional",
  "Please try again.": "Intente de nuevo.",
  "Quote this if you follow up.": "Menci\u00f3nelo si vuelve a preguntar.",
  "Report a problem with someone": "Reportar un problema con alguien",
  "Search by name": "Buscar por nombre",
  "Someone will be in touch with you within 72 hours.": "Alguien se comunicar\u00e1 con usted en un plazo de 72 horas.",
  "The staff list did not load. Try again in a minute.": "La lista del personal no carg\u00f3. Intente de nuevo en un minuto.",
  "We got your report.": "Recibimos su reporte.",
  "What happened": "Qu\u00e9 pas\u00f3",
  "Who is involved?": "\u00bfQui\u00e9n est\u00e1 involucrado?",
  "Who is it about? Pick at least one person.": "\u00bfSobre qui\u00e9n es? Elija al menos una persona.",
  "Write what happened in your own words. One sentence is enough.": "Escriba lo que pas\u00f3 con sus propias palabras. Con una frase basta.",
  "Yes": "S\u00ed",
  "You can write up to {max} characters.": "Puede escribir hasta {max} caracteres.",
  "Your reference": "Su n\u00famero de referencia",
  "Your report was not sent.": "Su reporte no se envi\u00f3.",
  "{used} of {max} characters used.": "{used} de {max} caracteres usados.",

  // Forms
  "Add row": "Agregar fila",
  "Answered": "Respondida",
  "Back": "Atr\u00e1s",
  "Check this answer": "Revise esta respuesta",
  "Continue": "Continuar",
  "Done": "Listo",
  "Edit": "Editar",
  "Forms": "Formularios",
  "Forms could not load. Check your signal and try again.": "Los formularios no cargaron. Revise su se\u00f1al e intente de nuevo.",
  "Keep filling": "Seguir llenando",
  "Leave": "Salir",
  "Leave this report? Your saved answers stay, and you can continue from Forms or Help.": "\u00bfSalir de este reporte? Sus respuestas guardadas se quedan y puede continuar desde Formularios o Ayuda.",
  "Loading forms": "Cargando formularios",
  "Next": "Siguiente",
  "No forms to fill right now.": "No hay formularios para llenar ahora.",
  "Not answered": "Sin responder",
  "Not saved yet. Check your signal and tap Next again.": "Todav\u00eda no se guard\u00f3. Revise su se\u00f1al y toque Siguiente otra vez.",
  "Not sent yet. Check your signal and tap Submit report again.": "Todav\u00eda no se envi\u00f3. Revise su se\u00f1al y toque Enviar reporte otra vez.",
  "Not signed": "Sin firmar",
  "Not signed yet. Check your signal and tap Sign again.": "Todav\u00eda no se firm\u00f3. Revise su se\u00f1al y toque Firmar otra vez.",
  "Not yet": "Todav\u00eda no",
  "Opening": "Abriendo",
  "Remove row": "Quitar fila",
  "Report": "Reportar",
  "Report sent. The people who handle these reports have been told.": "Reporte enviado. Ya se avis\u00f3 a las personas que atienden estos reportes.",
  "Required": "Obligatorio",
  "Review": "Revisar",
  "Row {n}": "Fila {n}",
  "Saving": "Guardando",
  "Section {n}": "Secci\u00f3n {n}",
  "Section {n} of {total}": "Secci\u00f3n {n} de {total}",
  "Send it": "Enviarlo",
  "Send this report? You cannot change it after it is sent.": "\u00bfEnviar este reporte? No lo podr\u00e1 cambiar despu\u00e9s de enviarlo.",
  "Sending": "Enviando",
  "Sign": "Firmar",
  "Signed by {name} on {date} at {time}": "Firmado por {name} el {date} a las {time}",
  "Start report": "Comenzar reporte",
  "These still need an answer": "Estas todav\u00eda necesitan respuesta",
  "This question cannot be answered here yet. Your supervisor will finish it.": "Esta pregunta todav\u00eda no se puede responder aqu\u00ed. Su supervisor la completar\u00e1.",
  "This report was already sent.": "Este reporte ya se hab\u00eda enviado.",
  "This table is full.": "Esta tabla est\u00e1 llena.",
  "Untitled report": "Reporte sin t\u00edtulo",
  "{answered} answered": "{answered} respondidas",
  "{answered} answered, {remaining} to go": "{answered} respondidas, faltan {remaining}",

  // Shortcuts
  "Add to bar": "Agregar a la barra",
  "Add to bar {name}": "Agregar {name} a la barra",
  "Always first": "Siempre primero",
  "Always last": "Siempre al final",
  "Everything is on your bar.": "Todo est\u00e1 en su barra.",
  "Home": "Inicio",
  "Move down": "Bajar",
  "Move down {name}": "Bajar {name}",
  "Move up": "Subir",
  "Move up {name}": "Subir {name}",
  "On your bar": "En su barra",
  "Pick something for this spot": "Elija algo para este lugar",
  "Put the bar back the way it came?": "\u00bfDejar la barra como estaba al principio?",
  "Remove": "Quitar",
  "Remove {name}": "Quitar a {name}",
  "Replace which one?": "\u00bfCu\u00e1l quiere reemplazar?",
  "Reset": "Restablecer",
  "Reset to default": "Volver a lo original",
  "Shortcuts": "Accesos directos",
  "Under More": "En M\u00e1s",
  "will take the place of the one you pick.": "tomar\u00e1 el lugar del que elija.",
  "Your bar is full.": "Su barra est\u00e1 llena.",
  "Remove {name} from the bar": "Quitar {name} de la barra",

  // Notifications
  "Load more": "Cargar m\u00e1s",
  "Mark all read": "Marcar todas como le\u00eddas",
  "Marking...": "Marcando...",
  "Nothing yet.": "Todav\u00eda no hay nada.",
  "Notifications did not load.": "Las notificaciones no cargaron.",
  "Open in the dashboard": "Abrir en el panel",

  // Settings
  "A": "A",
  "Appearance": "Apariencia",
  "Change PIN": "Cambiar PIN",
  "Choose how the app looks.": "Elija c\u00f3mo se ve la aplicaci\u00f3n.",
  "Choose what sits on your bottom bar. Everything else is under More.": "Elija qu\u00e9 va en su barra de abajo. Todo lo dem\u00e1s queda en M\u00e1s.",
  "Confirm New PIN": "Confirmar PIN nuevo",
  "Could not update your PIN.": "No se pudo actualizar su PIN.",
  "Current PIN": "PIN actual",
  "Dark": "Oscuro",
  "Light": "Claro",
  "Makes everything in the app bigger on this phone.": "Agranda todo en la aplicaci\u00f3n en este tel\u00e9fono.",
  "Makes everything in the app bigger.": "Agranda todo en la aplicaci\u00f3n.",
  "New PIN": "PIN nuevo",
  "Text size": "Tama\u00f1o del texto",
  "The app, Help and report forms use this language.": "La aplicaci\u00f3n, Ayuda y los formularios usan este idioma.",
  "Update PIN": "Actualizar PIN",
  "Your PIN is 4 digits. Choose one that only you know.": "Su PIN es de 4 d\u00edgitos. Elija uno que solo usted sepa.",
  "Enter your current 4-digit PIN.": "Escriba su PIN actual de 4 d\u00edgitos.",
  "Your new PIN must be different from your current PIN.": "Su PIN nuevo debe ser distinto de su PIN actual.",
  "That is not your current PIN.": "Ese no es su PIN actual.",
  "That PIN is too easy to guess. Choose a different one.": "Ese PIN es muy f\u00e1cil de adivinar. Elija uno distinto.",

  // Profile
  "Address": "Direcci\u00f3n",
  "Address Line 1": "Direcci\u00f3n l\u00ednea 1",
  "Address Line 2": "Direcci\u00f3n l\u00ednea 2",
  "Apt, suite, etc.": "Apartamento, suite, etc.",
  "Birthday": "Fecha de nacimiento",
  "City": "Ciudad",
  "Emergency Contact": "Contacto de emergencia",
  "Emergency Phone": "Tel\u00e9fono de emergencia",
  "Employee ID": "ID de empleado",
  "Employee ID not assigned. Ask your supervisor.": "No tiene ID de empleado asignado. Preg\u00fantele a su supervisor.",
  "Full name": "Nombre completo",
  "Loading profile...": "Cargando perfil...",
  "No shift": "Sin turno",
  "Not set": "Sin poner",
  "Personal Information": "Informaci\u00f3n personal",
  "Phone number": "N\u00famero de tel\u00e9fono",
  "Photo must be under 20MB": "La foto debe pesar menos de 20 MB",
  "Photo updated": "Foto actualizada",
  "Profile updated": "Perfil actualizado",
  "Save": "Guardar",
  "Site Assignments": "Sitios asignados",
  "Staff": "Personal",
  "State": "Estado",
  "Street address": "Calle y n\u00famero",
  "Zip": "C\u00f3digo postal",

  // API message
  "A part day needs both a start and an end time, on one day": "Parte de un d\u00eda necesita hora de inicio y hora de fin, en un solo d\u00eda",
  "A photo could not be read. Upload it again and resend it.": "Una foto no se pudo leer. S\u00fabala otra vez y vuelva a enviarla.",
  "A photo is larger than 5 MB. Send a smaller photo.": "Una foto pesa m\u00e1s de 5 MB. Env\u00ede una foto m\u00e1s peque\u00f1a.",
  "A photo must be a JPEG, PNG or WebP image.": "La foto debe ser una imagen JPEG, PNG o WebP.",
  "A sign-off is made with its own button": "La firma se hace con su propio bot\u00f3n",
  "Choose a type of time off": "Elija un tipo de tiempo libre",
  "Dates must be YYYY-MM-DD": "Las fechas deben ser YYYY-MM-DD",
  "Draft not found": "No se encontr\u00f3 el reporte",
  "Enter a real date": "Escriba una fecha real",
  "Enter a real time": "Escriba una hora real",
  "Form not found": "No se encontr\u00f3 el formulario",
  "Hours must be a number from 0 to 999.99": "Las horas deben ser un n\u00famero de 0 a 999.99",
  "Keep the reason to 1000 characters or fewer.": "Escriba el motivo en 1000 caracteres o menos.",
  "language must be en or es": "el idioma debe ser en o es",
  "One of the people picked is not on the staff list": "Una de las personas elegidas no est\u00e1 en la lista del personal",
  "Photo upload failed": "No se pudo subir la foto",
  "Pick at least one person this is about": "Elija al menos a una persona de quien trata este reporte",
  "Pick up to 10 people": "Elija hasta 10 personas",
  "Request failed": "La solicitud fall\u00f3",
  "Request not found": "No se encontr\u00f3 la solicitud",
  "Required fields are unanswered": "Faltan campos obligatorios por responder",
  "Say whether this is about someone in management": "Indique si esto es sobre alguien de la gerencia",
  "Send answers as an object of key and value": "Env\u00ede las respuestas como un objeto de clave y valor",
  "Send at most 3 photos with one message.": "Env\u00ede como m\u00e1ximo 3 fotos en un mensaje.",
  "Server error": "Error del servidor",
  "Session expired": "Su sesi\u00f3n venci\u00f3",
  "shortcuts must be four different tab ids": "los accesos directos deben ser cuatro pesta\u00f1as distintas",
  "Some answers are not valid": "Algunas respuestas no son v\u00e1lidas",
  "textSize must be standard, large, xlarge or largest": "el tama\u00f1o del texto debe ser standard, large, xlarge o largest",
  "That column is not on this form": "Esa columna no est\u00e1 en este formulario",
  "That is not a sign-off on this form": "Eso no es una firma de este formulario",
  "That photo was not uploaded by you. Upload the photo again and resend it.": "Esa foto no la subi\u00f3 usted. Suba la foto otra vez y vuelva a enviarla.",
  "That row is not on this form": "Esa fila no est\u00e1 en este formulario",
  "That table has no room for another row": "Esa tabla no tiene espacio para otra fila",
  "The last day cannot be before the first day": "El \u00faltimo d\u00eda no puede ser anterior al primer d\u00eda",
  "theme must be light or dark": "el tema debe ser light o dark",
  "These fields cannot be answered here": "Estos campos no se pueden responder aqu\u00ed",
  "This form is not available to you": "Este formulario no est\u00e1 disponible para usted",
  "This part is already signed": "Esta parte ya est\u00e1 firmada",
  "This report is already submitted": "Este reporte ya est\u00e1 enviado",
  "This report was already submitted": "Este reporte ya se hab\u00eda enviado",
  "This report was voided": "Este reporte fue anulado",
  "This request was already approved": "Esta solicitud ya estaba aprobada",
  "This request was already cancelled": "Esta solicitud ya estaba cancelada",
  "This request was already denied": "Esta solicitud ya estaba denegada",
  "Time off can start at most 30 days ago": "El tiempo libre puede comenzar 30 d\u00edas atr\u00e1s como m\u00e1ximo",
  "Time off can start at most one year ahead": "El tiempo libre puede comenzar un a\u00f1o adelante como m\u00e1ximo",
  "Times must be HH:MM, from 00:00 to 23:59": "Las horas deben ser HH:MM, de 00:00 a 23:59",
  "Upload failed": "No se pudo subir el archivo",
  "User not found": "No se encontr\u00f3 el usuario",
  "You already have time off requested or approved for those days": "Ya tiene tiempo libre solicitado o aprobado para esos d\u00edas",
  "You cannot pick yourself": "No puede elegirse a s\u00ed mismo",
  "You cannot sign this part of the form": "Usted no puede firmar esta parte del formulario",

  // Bar and More
  "Chat": "Mensajes",
  "Help": "Ayuda",
  "Inspect": "Inspecci\u00f3n",

  // notifAgo
  "now": "ahora",

  // Bar and More
  "Schedule": "Horario",
  "Speak Up": "Confianza",
  "Tasks": "Tareas",

  // notifAgo
  "{n}d": "{n} d",
  "{n}h": "{n} h",
  "{n}m": "{n} min",
  },
};

// {name} is replaced after the language is chosen, so the
// Spanish decides where a value lands rather than the English
// word order.
function fill(text, vars) {
  if (!vars) return text;
  return String(text).replace(/\{(\w+)\}/g, function (whole, key) {
    return Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : whole;
  });
}

// The one call every screen makes. Anything that is not a string
// comes back untouched, so a null or a number passed by mistake
// renders the way it did before.
export function tr(text, vars) {
  if (typeof text !== "string") return text;
  const table = WORDS[current];
  const out = table && Object.prototype.hasOwnProperty.call(table, text) ? table[text] : text;
  return fill(out, vars);
}

// What every date and time formatter passes.
export function dateLocale() {
  return current === "es" ? "es-US" : "en-US";
}
